---
title: "STA 101 Data Analysis and Statistical Inference"
subtitle: "Duke University Fall 2026"
execute: 
  freeze: false
editor_options: 
  chunk_output_type: console
editor: 
  mode: source
---

Below is a prospective outline for the course. Due dates are firm, but topics may change with advanced notice.

```{r}
#| echo: false
#| message: false
#| warning: false
library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1fISQ-TZpEbdcB1XUypBWOfNfkCk653gI-L3oVUC3tII/edit?usp=sharing", sheet = "101")
```

```{r}
#| echo: false
#| column: screen-inset-right

table_width <- 82

d |>
  filter(!is.na(session)) |>
  select(-dow, -admin_notes, -number, -session) |>
  mutate(
    date = as.Date(date),
    ) |>
  gt() |>
  fmt_date(date, date_style = 31) |>
  sub_missing(
    columns = c(week, more, topic, reading, materials, due), 
    missing_text = ""
  ) |>
  cols_align(
    align = "center", 
    columns = c(week)
  ) |>
  cols_align(
    align = "right", 
    columns = c(date)
  ) |>
  cols_align(
    align = "left", 
    columns = c(topic, more, materials, due, reading)
  ) |>
#  tab_style(
#    style = cell_text(
#      color = "#b4b4b4"
#    ),
#    locations = cells_body(
#      columns = c(more),
#      rows = more == "*To be posted*"
#    )
#  ) |>
#  tab_style(
#    style = cell_text(
#      color = "#b4b4b4"
#    ),
#    locations = cells_body(
#      columns = c(materials),
#      rows = materials == "*To be posted*"
#    )
#  ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, more, materials, reading)
    )
  ) |>
  tab_style(
    style = cell_borders(
      sides = "top",
      color = "black",
      weight = px(2),
      style = "solid"
    ),
    locations = cells_body(
      columns = everything(),
      rows = !is.na(week) 
      # puts black line above rows where certain keywords are detected in certain columns
    )
  ) |>
  fmt_markdown(
    columns = c(topic, more, materials, due, reading)
  ) |>
  # this gets all the hyperlinks and line breaks twerkin
  tab_options(table.width = pct(table_width),
              table.align = 'left') |>
  cols_width(
    week ~ pct(.02 * table_width),
    date ~ pct(.10 * table_width), 
    topic ~ pct(.25 * table_width),
    materials ~ pct(.07 * table_width),
    reading ~ pct(.15 * table_width), 
    more ~ pct(.25 * table_width),
    due ~ pct(.16 * table_width)
  ) |>
  cols_label_with(fn = function(x) {
      janitor::make_clean_names(x, case = "title") |>
        toupper() |>
        stringr::str_replace_all("^|$", "**") |>
        md()
    }) |>
  tab_options(table.font.size = 13) |>
  opt_row_striping()
# I have no clue what this last thing does
```





