<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-c8ad9e5dbd60b7b70b38521ab19b7da4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<meta name="shinylive:serviceworker_dir" content="..">
<script src="../site_libs/quarto-contrib/shinylive-0.9.1/shinylive/load-shinylive-sw.js" type="module"></script>
<script src="../site_libs/quarto-contrib/shinylive-0.9.1/shinylive/run-python-blocks.js" type="module"></script>
<link href="../site_libs/quarto-contrib/shinylive-0.9.1/shinylive/shinylive.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/shinylive-quarto-css/shinylive-quarto.css" rel="stylesheet"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">
<meta name="author" content="John Zito">
<meta name="dcterms.date" content="2026-09-29">
<title>STA 101 Fall 2026 – Logistic regression 1</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
<style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
<link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f0195dcd610196b9111c6e10e98695f4.css">
<link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
<style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Logistic regression 1 – STA 101 Fall 2026">
<meta property="og:description" content="Lecture 9">
<meta property="og:site_name" content="STA 101 Fall 2026">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center"><h1 class="title">Logistic regression 1</h1>
  <p class="subtitle">Lecture 9</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
John Zito 
</div>
        <p class="quarto-title-affiliation">
            Duke University <br> STA 101 Fall 2026
          </p>
    </div>
</div>

  <p class="date">2026-09-29</p>
</section><section><section id="so-where-were-we" class="title-slide slide level1 center"><h1>So where were we…</h1>

</section><section id="thus-far" class="slide level2"><h2>Thus far…</h2>
<p>We have been studying regression:</p>
<ul>
<li><p>What combinations of data types have we seen?</p></li>
<li><p>What did the picture look like?</p></li>
</ul></section><section id="recap-simple-linear-regression" class="slide level2"><h2>Recap: simple linear regression</h2>
<p>Numerical response and one numerical predictor:</p>

<img data-src="09-logistic-1_files/figure-revealjs/slr-1-1.png" width="960" class="r-stretch"></section><section id="recap-simple-linear-regression-1" class="slide level2"><h2>Recap: simple linear regression</h2>
<p>Numerical response and one categorical predictor (two levels):</p>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-1-1.png" width="960" class="r-stretch"></section><section id="recap-multiple-linear-regression" class="slide level2"><h2>Recap: multiple linear regression</h2>
<p>Numerical response; numerical and categorical predictors:</p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img data-src="09-logistic-1_files/figure-revealjs/additive-interaction-viz-1.png" width="960"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img data-src="09-logistic-1_files/figure-revealjs/additive-interaction-viz-2.png" width="960"></p>
</div>
</div>
</div>
</section><section id="today-a-binary-response" class="slide level2 smaller"><h2>Today: a <em>binary</em> response</h2>
<p><span class="math display">\[
y =
\begin{cases}
1 &amp; &amp;&amp;\text{eg. Yes, Win, True, Heads, Success}\\
0 &amp; &amp;&amp;\text{eg. No, Lose, False, Tails, Failure}.
\end{cases}
\]</span></p>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-2-1.png" width="960" class="r-stretch"></section><section id="who-cares" class="slide level2"><h2>Who cares?</h2>
<p>If we can model the relationship between predictors (<span class="math inline">\(x\)</span>) and a binary response (<span class="math inline">\(y\)</span>), we can use the model to do a special kind of prediction called <em>classification</em>.</p>
</section><section id="example-is-the-e-mail-spam-or-not" class="slide level2 smaller"><h2>Example: is the e-mail spam or not?</h2>
<p><span class="math display">\[
\mathbf{x}: \text{word and character counts in an e-mail.}
\]</span></p>

<img data-src="images/09/spam.png" class="quarto-figure quarto-figure-center r-stretch" style="width:70.0%"><p><span class="math display">\[
y
=
\begin{cases}
1 &amp; \text{it's spam}\\
0 &amp; \text{it's legit}
\end{cases}
\]</span></p>
</section><section id="example-is-it-pneumonia-or-not" class="slide level2 smaller"><h2>Example: is it pneumonia or not?</h2>
<p><span class="math display">\[
\mathbf{x}: \text{features in a medical image.}
\]</span></p>

<img data-src="images/09/pneumonia.png" class="quarto-figure quarto-figure-center r-stretch"><p><span class="math display">\[
y
=
\begin{cases}
1 &amp; \text{it's pneumonia}\\
0 &amp; \text{it's healthy}
\end{cases}
\]</span></p>
</section><section id="example-will-they-default" class="slide level2 smaller"><h2>Example: will they default?</h2>
<p><span class="math display">\[
\mathbf{x}: \text{financial and demographic info about a loan applicant.}
\]</span></p>

<img data-src="images/09/fico.jpg" class="quarto-figure quarto-figure-center r-stretch" style="width:60.0%"><p><span class="math display">\[
y
=
\begin{cases}
1 &amp; \text{applicant is at risk of defaulting on loan}\\
0 &amp; \text{applicant is safe}
\end{cases}
\]</span></p>
</section><section id="example-who-said-it-ts-or-ws" class="slide level2 smaller"><h2>Example: Who said it: TS or WS?</h2>
<p><span class="math display">\[
\mathbf{x}: \text{word counts (e.g., thou, love, heartbreak), stylistic features}
\]</span></p>

<img data-src="images/09/tswift.png" class="quarto-figure quarto-figure-center r-stretch" style="width:40.0%"><p><span class="math display">\[
y
=
\begin{cases}
1 &amp; \text{Taylor Swift}\\
0 &amp; \text{William Shakespeare}
\end{cases}
\]</span></p>
</section><section id="how-do-we-model-this-type-of-data" class="slide level2"><h2>How do we model this type of data?</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section><section id="straight-line-of-best-fit-is-a-little-silly" class="slide level2"><h2>Straight line of best fit is a little silly</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"><p>Possible, but silly.</p>
</section><section id="instead-s-curve-of-best-fit" class="slide level2 smaller"><h2>Instead: S-curve of best fit</h2>
<p>Instead of modeling <span class="math inline">\(y\)</span> directly, we model the probability that <span class="math inline">\(y=1\)</span>:</p>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-5-1.png" width="960" class="r-stretch"><ul>
<li>“Given new email, what’s the probability that it’s spam?’’</li>
<li>“Given new image, what’s the probability that it’s pneumonia?’’</li>
<li>“Given new loan application, what’s the probability that they default?’’</li>
</ul></section><section id="why-dont-we-model-y-directly" class="slide level2"><h2>Why don’t we model y directly?</h2>
<ul>
<li>
<p><strong>Recall regression with a numerical response</strong>:</p>
<ul>
<li>Our models do not output <em>guarantees</em> for <span class="math inline">\(y\)</span>, they output predictions that describe behavior <em>on average</em>;</li>
</ul>
</li>
<li>
<p><strong>Similar when modeling a binary response</strong>:</p>
<ul>
<li>Our models cannot directly guarantee that <span class="math inline">\(y\)</span> will be zero or one. The correct analog to “on average” for a 0/1 response is “what’s the probability?”</li>
</ul>
</li>
</ul></section></section><section><section id="so-what-is-this-s-curve-anyway" class="title-slide slide level1 center"><h1>So, what is this S-curve, anyway?</h1>

</section><section id="its-the-logistic-function" class="slide level2"><h2>It’s the <em>logistic function</em>
</h2>
<p><span class="math display">\[
\text{Prob}(y = 1\mid x)
=
\frac{e^{\beta_0+\beta_1x}}{1+e^{\beta_0+\beta_1x}}.
\]</span></p>
<p>If you set <span class="math inline">\(p = \text{Prob}(y = 1\mid x)\)</span> and do some algebra, you get the simple linear model for the <em>log-odds</em>:</p>
<p><span class="math display">\[
\log\left(\frac{p}{1-p}\right)
=
\beta_0+\beta_1x.
\]</span></p>
<p>This is called the <em>logistic regression</em> model.</p>
</section><section id="log-odds" class="slide level2 medium scrollable"><h2>Log-odds?</h2>
<ul>
<li class="fragment">
<span class="math inline">\(p = \text{Prob}(y = 1 \mid x)\)</span> is a probability. A number between 0 and 1;</li>
<li class="fragment">
<span class="math inline">\(o=p / (1 - p)\)</span> is the odds. A number between 0 and <span class="math inline">\(\infty\)</span>;
<ul>
<li class="fragment">This is just an alternative way of communicating the probability: “The odds of this lecture going well are 10 to 1;”</li>
</ul>
</li>
<li class="fragment">The log odds <span class="math inline">\(\log(o)=\log(p / (1 - p))\)</span> is a number between <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span>, which is suitable for the linear model;</li>
<li class="fragment">Why does this “transformation” work? The log function maps positive numbers <span class="math inline">\((0, \infty)\)</span> to all real numbers <span class="math inline">\((-\infty, \infty)\)</span>.</li>
</ul></section><section id="probability-to-odds" class="slide level2"><h2>Probability to odds</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-6-1.png" width="960" class="r-stretch"></section><section id="zooming-in" class="slide level2"><h2>Zooming in</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section><section id="odds-to-log-odds" class="slide level2"><h2>Odds to log odds</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-8-1.png" width="960" class="r-stretch"></section><section id="put-it-all-together" class="slide level2 small"><h2>Put it all together</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure><p><img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-9-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<ul>
<li>
<span class="math inline">\(p = 0 \to \text{log-odds}=-\infty\)</span>;</li>
<li>
<span class="math inline">\(p = 1/2 \to \text{log-odds}=0\)</span>;</li>
<li>
<span class="math inline">\(p = 1 \to \text{log-odds}=\infty\)</span>;</li>
<li>And everything in between.</li>
</ul>
<p>The log-odds transformation takes probabilities between 0 and 1 and streeetches them out to numbers between <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span>, for which the linear model is appropriate.</p>
</div></div>
</section><section id="logistic-regression" class="slide level2"><h2>Logistic regression</h2>
<p><span class="math display">\[
\log\left(\frac{p}{1-p}\right)
=
\beta_0+\beta_1x.
\]</span></p>
<ul>
<li><p>The <em>logit</em> function <span class="math inline">\(\log(p / (1-p))\)</span> is an example of a <em>link function</em> that transforms the linear model to have an appropriate range;</p></li>
<li><p>This is an example of a <em>generalized linear model</em>. Take a class like STA 210 to learn more.</p></li>
</ul></section><section id="how-do-the-parameters-control-the-shape" class="slide level2 scrollable"><h2>How do the parameters control the shape?</h2>
<p><span class="math display">\[
p
=
\frac{e^{\beta_0+\beta_1x}}{1+e^{\beta_0+\beta_1x}} \quad \Longleftrightarrow\quad \log\left(\frac{p}{1-p}\right)
=
\beta_0+\beta_1x.
\]</span></p>
<div class="sourceCode" id="cb1" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb1-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb1-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb1-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb1-4"><a></a>#| standalone: true</span>
<span id="cb1-5"><a></a>#| viewerHeight: 500</span>
<span id="cb1-6"><a></a></span>
<span id="cb1-7"><a></a>library(shiny)</span>
<span id="cb1-8"><a></a></span>
<span id="cb1-9"><a></a>ui &lt;- fluidPage(</span>
<span id="cb1-10"><a></a>  </span>
<span id="cb1-11"><a></a>  titlePanel("Adjusting the shape of the S-curve"),</span>
<span id="cb1-12"><a></a>  </span>
<span id="cb1-13"><a></a>  sidebarLayout(</span>
<span id="cb1-14"><a></a>    sidebarPanel(</span>
<span id="cb1-15"><a></a>      sliderInput("b0",</span>
<span id="cb1-16"><a></a>                  "β₀",</span>
<span id="cb1-17"><a></a>                  min = -5,</span>
<span id="cb1-18"><a></a>                  max = 5,</span>
<span id="cb1-19"><a></a>                  value = 0,</span>
<span id="cb1-20"><a></a>                  step = 0.1),</span>
<span id="cb1-21"><a></a>      sliderInput("b1",</span>
<span id="cb1-22"><a></a>                  "β₁",</span>
<span id="cb1-23"><a></a>                  min = -5,</span>
<span id="cb1-24"><a></a>                  max = 5,</span>
<span id="cb1-25"><a></a>                  value = 1,</span>
<span id="cb1-26"><a></a>                  step = 0.1)</span>
<span id="cb1-27"><a></a>    ),</span>
<span id="cb1-28"><a></a>    </span>
<span id="cb1-29"><a></a>    mainPanel(</span>
<span id="cb1-30"><a></a>      plotOutput("distPlot")</span>
<span id="cb1-31"><a></a>    )</span>
<span id="cb1-32"><a></a>  )</span>
<span id="cb1-33"><a></a>)</span>
<span id="cb1-34"><a></a></span>
<span id="cb1-35"><a></a># Define server logic required to draw a histogram</span>
<span id="cb1-36"><a></a>server &lt;- function(input, output) {</span>
<span id="cb1-37"><a></a>  </span>
<span id="cb1-38"><a></a>  output$distPlot &lt;- renderPlot({</span>
<span id="cb1-39"><a></a>    </span>
<span id="cb1-40"><a></a>    b0 &lt;- input$b0</span>
<span id="cb1-41"><a></a>    b1 &lt;- input$b1</span>
<span id="cb1-42"><a></a></span>
<span id="cb1-43"><a></a>    curve(exp(b0 + b1 * x) / (1 + exp(b0 + b1 * x)), from = -5, to = 5, n = 1000, col = "red", bty = "n", ylab = "Prob(y = 1 | x)", xlab = "x", ylim = c(0, 1), lwd = 5)</span>
<span id="cb1-44"><a></a>    abline(v = 0)</span>
<span id="cb1-45"><a></a>    points(0, exp(b0) / (1 + exp(b0)), pch = 19, col = "red", cex = 2)</span>
<span id="cb1-46"><a></a>  })</span>
<span id="cb1-47"><a></a>}</span>
<span id="cb1-48"><a></a></span>
<span id="cb1-49"><a></a># Run the application </span>
<span id="cb1-50"><a></a>shinyApp(ui = ui, server = server)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section></section><section><section id="estimation" class="title-slide slide level1 center"><h1>Estimation</h1>

</section><section id="estimation-picking-the-best-fitting-s-curve" class="slide level2 scrollable"><h2>Estimation: picking the “best fitting” S-curve</h2>
<div class="sourceCode" id="cb2" data-engine="r"><pre class="sourceCode numberSource shinylive-r number-lines code-with-copy"><code class="sourceCode"><span id="cb2-1"><a></a>#| '!! shinylive warning !!': |</span>
<span id="cb2-2"><a></a>#|   shinylive does not work in self-contained HTML documents.</span>
<span id="cb2-3"><a></a>#|   Please set `embed-resources: false` in your metadata.</span>
<span id="cb2-4"><a></a>#| standalone: true</span>
<span id="cb2-5"><a></a>#| viewerHeight: 500</span>
<span id="cb2-6"><a></a></span>
<span id="cb2-7"><a></a>library(shiny)</span>
<span id="cb2-8"><a></a></span>
<span id="cb2-9"><a></a>ui &lt;- fluidPage(</span>
<span id="cb2-10"><a></a>  </span>
<span id="cb2-11"><a></a>  titlePanel("Guess the best-fitting logistic curve"),</span>
<span id="cb2-12"><a></a>  </span>
<span id="cb2-13"><a></a>  sidebarLayout(</span>
<span id="cb2-14"><a></a>    sidebarPanel(</span>
<span id="cb2-15"><a></a>      </span>
<span id="cb2-16"><a></a>      actionButton("new_data", "Generate new data"),</span>
<span id="cb2-17"><a></a>      </span>
<span id="cb2-18"><a></a>      br(), br(),</span>
<span id="cb2-19"><a></a>      </span>
<span id="cb2-20"><a></a>      sliderInput("b0",</span>
<span id="cb2-21"><a></a>                  "b₀",</span>
<span id="cb2-22"><a></a>                  min = -5,</span>
<span id="cb2-23"><a></a>                  max = 5,</span>
<span id="cb2-24"><a></a>                  value = 0,</span>
<span id="cb2-25"><a></a>                  step = 0.1),</span>
<span id="cb2-26"><a></a>      </span>
<span id="cb2-27"><a></a>      sliderInput("b1",</span>
<span id="cb2-28"><a></a>                  "b₁",</span>
<span id="cb2-29"><a></a>                  min = -5,</span>
<span id="cb2-30"><a></a>                  max = 5,</span>
<span id="cb2-31"><a></a>                  value = 1,</span>
<span id="cb2-32"><a></a>                  step = 0.1),</span>
<span id="cb2-33"><a></a>      </span>
<span id="cb2-34"><a></a>      checkboxInput("show_mle",</span>
<span id="cb2-35"><a></a>                    "Show MLE",</span>
<span id="cb2-36"><a></a>                    value = FALSE)</span>
<span id="cb2-37"><a></a>    ),</span>
<span id="cb2-38"><a></a>    </span>
<span id="cb2-39"><a></a>    mainPanel(</span>
<span id="cb2-40"><a></a>      plotOutput("distPlot"),</span>
<span id="cb2-41"><a></a>      verbatimTextOutput("mle_output")</span>
<span id="cb2-42"><a></a>    )</span>
<span id="cb2-43"><a></a>  )</span>
<span id="cb2-44"><a></a>)</span>
<span id="cb2-45"><a></a></span>
<span id="cb2-46"><a></a>server &lt;- function(input, output) {</span>
<span id="cb2-47"><a></a>  </span>
<span id="cb2-48"><a></a>  # Store simulated data</span>
<span id="cb2-49"><a></a>  sim_data &lt;- reactiveVal()</span>
<span id="cb2-50"><a></a>  </span>
<span id="cb2-51"><a></a>  # Function to generate a new dataset</span>
<span id="cb2-52"><a></a>  generate_data &lt;- function() {</span>
<span id="cb2-53"><a></a>    </span>
<span id="cb2-54"><a></a>    # Prior on parameters, restricted to slider bounds</span>
<span id="cb2-55"><a></a>    b0_true &lt;- runif(1, -5, 5)</span>
<span id="cb2-56"><a></a>    b1_true &lt;- runif(1, -5, 5)</span>
<span id="cb2-57"><a></a>    </span>
<span id="cb2-58"><a></a>    # Simulate x values</span>
<span id="cb2-59"><a></a>    n &lt;- 100</span>
<span id="cb2-60"><a></a>    x &lt;- runif(n, -5, 5)</span>
<span id="cb2-61"><a></a>    </span>
<span id="cb2-62"><a></a>    # Logistic probabilities</span>
<span id="cb2-63"><a></a>    p &lt;- plogis(b0_true + b1_true * x)</span>
<span id="cb2-64"><a></a>    </span>
<span id="cb2-65"><a></a>    # Simulate y values</span>
<span id="cb2-66"><a></a>    y &lt;- rbinom(n, size = 1, prob = p)</span>
<span id="cb2-67"><a></a>    </span>
<span id="cb2-68"><a></a>    data.frame(</span>
<span id="cb2-69"><a></a>      x = x,</span>
<span id="cb2-70"><a></a>      y = y,</span>
<span id="cb2-71"><a></a>      b0_true = b0_true,</span>
<span id="cb2-72"><a></a>      b1_true = b1_true</span>
<span id="cb2-73"><a></a>    )</span>
<span id="cb2-74"><a></a>  }</span>
<span id="cb2-75"><a></a>  </span>
<span id="cb2-76"><a></a>  # Generate initial data when app starts</span>
<span id="cb2-77"><a></a>  sim_data(generate_data())</span>
<span id="cb2-78"><a></a>  </span>
<span id="cb2-79"><a></a>  # Generate new data when button pressed</span>
<span id="cb2-80"><a></a>  observeEvent(input$new_data, {</span>
<span id="cb2-81"><a></a>    sim_data(generate_data())</span>
<span id="cb2-82"><a></a>  })</span>
<span id="cb2-83"><a></a>  </span>
<span id="cb2-84"><a></a>  output$distPlot &lt;- renderPlot({</span>
<span id="cb2-85"><a></a>    </span>
<span id="cb2-86"><a></a>    d &lt;- sim_data()</span>
<span id="cb2-87"><a></a>    </span>
<span id="cb2-88"><a></a>    b0 &lt;- input$b0</span>
<span id="cb2-89"><a></a>    b1 &lt;- input$b1</span>
<span id="cb2-90"><a></a>    </span>
<span id="cb2-91"><a></a>    # Plot the data</span>
<span id="cb2-92"><a></a>    plot(d$x, d$y,</span>
<span id="cb2-93"><a></a>         xlim = c(-5, 5),</span>
<span id="cb2-94"><a></a>         ylim = c(-0.05, 1.05),</span>
<span id="cb2-95"><a></a>         pch = 19,</span>
<span id="cb2-96"><a></a>         xlab = "x",</span>
<span id="cb2-97"><a></a>         ylab = "y",</span>
<span id="cb2-98"><a></a>         bty = "n")</span>
<span id="cb2-99"><a></a>    </span>
<span id="cb2-100"><a></a>    # User's curve</span>
<span id="cb2-101"><a></a>    curve(plogis(b0 + b1 * x),</span>
<span id="cb2-102"><a></a>          from = -5,</span>
<span id="cb2-103"><a></a>          to = 5,</span>
<span id="cb2-104"><a></a>          add = TRUE,</span>
<span id="cb2-105"><a></a>          col = "red",</span>
<span id="cb2-106"><a></a>          lwd = 5,</span>
<span id="cb2-107"><a></a>          n = 1000)</span>
<span id="cb2-108"><a></a>    </span>
<span id="cb2-109"><a></a>    abline(v = 0)</span>
<span id="cb2-110"><a></a>    </span>
<span id="cb2-111"><a></a>    points(0, plogis(b0),</span>
<span id="cb2-112"><a></a>           pch = 19,</span>
<span id="cb2-113"><a></a>           col = "red",</span>
<span id="cb2-114"><a></a>           cex = 2)</span>
<span id="cb2-115"><a></a>    </span>
<span id="cb2-116"><a></a>    # MLE curve</span>
<span id="cb2-117"><a></a>    if (input$show_mle) {</span>
<span id="cb2-118"><a></a>      </span>
<span id="cb2-119"><a></a>      fit &lt;- glm(y ~ x, data = d, family = binomial)</span>
<span id="cb2-120"><a></a>      mle &lt;- coef(fit)</span>
<span id="cb2-121"><a></a>      </span>
<span id="cb2-122"><a></a>      curve(plogis(mle[1] + mle[2] * x),</span>
<span id="cb2-123"><a></a>            from = -5,</span>
<span id="cb2-124"><a></a>            to = 5,</span>
<span id="cb2-125"><a></a>            add = TRUE,</span>
<span id="cb2-126"><a></a>            col = "blue",</span>
<span id="cb2-127"><a></a>            lwd = 3,</span>
<span id="cb2-128"><a></a>            lty = 2,</span>
<span id="cb2-129"><a></a>            n = 1000)</span>
<span id="cb2-130"><a></a>    }</span>
<span id="cb2-131"><a></a>  })</span>
<span id="cb2-132"><a></a>  </span>
<span id="cb2-133"><a></a>  # MLE coefficient display</span>
<span id="cb2-134"><a></a>  output$mle_output &lt;- renderText({</span>
<span id="cb2-135"><a></a>    </span>
<span id="cb2-136"><a></a>    if (!input$show_mle) {</span>
<span id="cb2-137"><a></a>      return(NULL)</span>
<span id="cb2-138"><a></a>    }</span>
<span id="cb2-139"><a></a>    </span>
<span id="cb2-140"><a></a>    d &lt;- sim_data()</span>
<span id="cb2-141"><a></a>    fit &lt;- glm(y ~ x, data = d, family = binomial)</span>
<span id="cb2-142"><a></a>    mle &lt;- coef(fit)</span>
<span id="cb2-143"><a></a>    </span>
<span id="cb2-144"><a></a>    paste0(</span>
<span id="cb2-145"><a></a>      "MLE:  b₀ = ", round(mle[1], 2),</span>
<span id="cb2-146"><a></a>      "    b₁ = ", round(mle[2], 2)</span>
<span id="cb2-147"><a></a>    )</span>
<span id="cb2-148"><a></a>  })</span>
<span id="cb2-149"><a></a>}</span>
<span id="cb2-150"><a></a></span>
<span id="cb2-151"><a></a>shinyApp(ui = ui, server = server)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section><section id="estimation-1" class="slide level2 medium"><h2>Estimation</h2>
<ul>
<li>Just like least squares linear regression, the problem of finding the “best-fitting” S-curve can be made mathematically precise and solved with calculus;</li>
<li>That’s not your problem. Trust that the computer knows what to do;</li>
<li>Given messy, incomplete, imperfect data, the fitted curve is:</li>
</ul>
<p><span class="math display">\[
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right)
=
b_0+b_1x.
\]</span></p>
<ul>
<li>
<span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are our best guess estimates of the ideal but unknown <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</li>
</ul></section><section id="todays-data" class="slide level2 smaller"><h2>Today’s data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>email <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">c</span>(spam, dollar, viagra, winner, password, exclaim_mess)) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,921
Columns: 6
$ spam         &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ dollar       &lt;dbl&gt; 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 5, 0, 0, …
$ viagra       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ winner       &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, n…
$ password     &lt;dbl&gt; 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …
$ exclaim_mess &lt;dbl&gt; 0, 1, 6, 48, 1, 1, 1, 18, 1, 0, 2, 1, 0, 10, 4, 10, 20, 0…</code></pre>
</div>
</div>
</section><section id="fitting-a-logistic-model" class="slide level2"><h2>Fitting a logistic model</h2>
<p><em>Very</em> similar to code you have already seen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>logistic_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a></a>  <span class="fu">fit</span>(spam <span class="sc">~</span> exclaim_mess, <span class="at">data =</span> email)</span>
<span id="cb5-3"><a></a></span>
<span id="cb5-4"><a></a><span class="fu">tidy</span>(logistic_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term          estimate std.error statistic p.value
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)  -2.27      0.0553     -41.1     0    
2 exclaim_mess  0.000272  0.000949     0.287   0.774</code></pre>
</div>
</div>
<p>Fitted equation for the log-odds:</p>
<p><span class="math display">\[
\log\left(\frac{\hat{p}}{1-\hat{p}}\right)
=
-2.27
+
0.000272\times exclaim~mess
\]</span></p>
</section></section><section><section id="interpretation" class="title-slide slide level1 center"><h1>Interpretation</h1>

</section><section id="recall-simple-linear-regression" class="slide level2"><h2>Recall: simple linear regression</h2>
<p><span class="math display">\[
\hat{y}=b_0+b_1x.
\]</span></p>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-12-1.png" width="960" class="r-stretch"></section><section id="the-intercept-in-linear-regression" class="slide level2"><h2>The intercept in linear regression</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-13-1.png" width="960" class="r-stretch"><p>It’s the model’s prediction for <span class="math inline">\(y\)</span> when <span class="math inline">\(x=0\)</span>.</p>
</section><section id="the-intercept-in-linear-regression-1" class="slide level2"><h2>The intercept in linear regression</h2>
<p>Plug in <span class="math inline">\(x=0\)</span> and simplify:</p>
<p><span class="math display">\[
\hat{y}=b_0+b_1\cdot 0=b_0.
\]</span></p>
<p>If <span class="math inline">\(x=0\)</span>, we predict <span class="math inline">\(y\)</span> will be <span class="math inline">\(b_0\)</span> on average.</p>
</section><section id="the-slope-in-linear-regression" class="slide level2"><h2>The slope in linear regression</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-14-1.png" width="960" class="r-stretch"><p>How does the prediction change when you change the input?</p>
</section><section id="the-slope-in-linear-regression-1" class="slide level2"><h2>The slope in linear regression</h2>
<p>At <span class="math inline">\(x\)</span>, you predict:</p>
<p><span class="math display">\[
\hat{y}^{(\text{old})} = b_0+b_1x.
\]</span></p>
<div class="fragment">
<p>At <span class="math inline">\(x + 1\)</span>, you predict:</p>
<p><span class="math display">\[
\hat{y}^{(\text{new})} = b_0+b_1(x+1) = b_0+b_1x+b_1=\hat{y}^{(\text{old})}+b_1.
\]</span></p>
</div>
<div class="fragment">
<p>So when the predictor shifts from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span>, the slope <span class="math inline">\(b_1\)</span> tells you the <em>additive</em> adjustment you must make to go from the old prediction to the new one. It’s the same adjustment regardless the <span class="math inline">\(x\)</span> you start from.</p>
</div>
</section><section id="the-intercept-in-logistic-regression" class="slide level2"><h2>The “intercept” in logistic regression</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-15-1.png" width="960" class="r-stretch"><p>The “intercept” determines what the model predicts when x = 0.</p>
</section><section id="the-intercept-in-logistic-regression-1" class="slide level2"><h2>The “intercept” in logistic regression</h2>
<p>Plug in <span class="math inline">\(x=0\)</span> and simplify the formula:</p>
<p><span class="math display">\[
\hat{p}=\widehat{P(y=1\mid x = 0)}=\frac{e^{b_0+b_1\times 0}}{1+e^{b_0+b_1\times 0}}=\frac{e^{b_0}}{1+e^{b_0}}.
\]</span></p>
<p>If <span class="math inline">\(x=0\)</span>, we predict that on average <span class="math inline">\(y=1\)</span> with probability <span class="math inline">\(\frac{e^{b_0}}{1+e^{b_0}}\)</span>.</p>
</section><section id="for-our-example" class="slide level2"><h2>For our example</h2>
<p><span class="math display">\[
\log\left(\frac{\hat{p}}{1-\hat{p}}\right)
=
-2.27
+
0.000272\times exclaim~mess
\]</span></p>
<p>If <code>exclaim_mess = 0</code>, then</p>
<p><span class="math display">\[
\hat{p}=\widehat{P(y=1\mid x = 0)}=\frac{e^{-2.27}}{1+e^{-2.27}}\approx 0.09.
\]</span></p>
<p>So, our model predicts that an email with no exclamation marks has a 9% probability of being spam.</p>
</section><section id="the-slope-in-logistic-regression" class="slide level2"><h2>The “slope” in logistic regression</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-16-1.png" width="960" class="r-stretch"><p>How does the prediction change when you change the input?</p>
</section><section id="the-slope-in-logistic-regression-1" class="slide level2"><h2>The “slope” in logistic regression</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-17-1.png" width="960" class="r-stretch"><p>Does the adjustment depend on the <span class="math inline">\(x\)</span> you’re starting from?</p>
</section><section id="three-versions-of-the-same-model" class="slide level2 medium"><h2>Three versions of the same model</h2>
<p>Probability:</p>
<p><span class="math display">\[
\hat{p}
=
\frac{e^{b_0+b_1x}}{1+e^{b_0+b_1x}}.
\]</span></p>
<p>Odds:</p>
<p><span class="math display">\[
\hat{o}=\frac{\widehat{p}}{1-\widehat{p}}=e^{b_0+b_1 x}.
\]</span></p>
<p>Log-odds:</p>
<p><span class="math display">\[
\log\left(\hat{o}\right)
=
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right)
=
b_0+b_1x.
\]</span></p>
</section><section id="how-do-the-log-odds-adjust" class="slide level2 scrollable"><h2>How do the log-odds adjust?</h2>
<p>At <span class="math inline">\(x\)</span>, you predict:</p>
<p><span class="math display">\[
\log\left(\hat{o}^{(\text{old})}\right)
=
b_0+b_1x.
\]</span></p>
<div class="fragment">
<p>At <span class="math inline">\(x + 1\)</span>, you predict:</p>
<p><span class="math display">\[
\begin{aligned}
\log\left(\hat{o}^{(\text{new})}\right)
&amp;=
b_0+b_1(x+1)\\
&amp;=
b_0+b_1x+b_1
\\
&amp;=
\log\left(\hat{o}^{(\text{old})}\right)+b_1.
\end{aligned}
\]</span></p>
</div>
<div class="fragment">
<p>Just like in linear regression, when the predictor shifts from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span>, the “slope” <span class="math inline">\(b_1\)</span> tell you the additive adjustment you must make to go from the old <strong>log-odds</strong> to the new <strong>log-odds</strong>. It’s the same adjustment regardless the <span class="math inline">\(x\)</span> you start from.</p>
</div>
</section><section id="how-do-the-odds-adjust" class="slide level2 scrollable"><h2>How do the odds adjust?</h2>
<p>At <span class="math inline">\(x\)</span>, you predict:</p>
<p><span class="math display">\[
\hat{o}^{(\text{old})}
=
e^{b_0+b_1x}.
\]</span></p>
<div class="fragment">
<p>At <span class="math inline">\(x + 1\)</span>, you predict:</p>
<p><span class="math display">\[
\hat{o}^{(\text{new})}
=
e^{b_0+b_1(x+1)}
=
e^{b_0+b_1x+b_1}
=
e^{b_0+b_1x}e^{b_1}
=
\hat{o}^{(\text{old})}\times e^{b_1}
.
\]</span></p>
</div>
<div class="fragment">
<p>When the predictor shifts from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span>, the <em>transformed</em> “slope” <span class="math inline">\(e^{b_1}\)</span> tell you the <em>multiplicative</em> adjustment you must make to go from the old <strong>odds</strong> to the new <strong>odds</strong>. It’s the same adjustment regardless the <span class="math inline">\(x\)</span> you start from.</p>
</div>
</section><section id="wut" class="slide level2"><h2>wut</h2>
<p>We have this:</p>
<p><span class="math display">\[
\hat{o}^{(\text{new})}
=
\hat{o}^{(\text{old})}\times e^{b_1}
.
\]</span></p>
<ul>
<li class="fragment">If <span class="math inline">\(b_1=0\)</span>, then <span class="math inline">\(e^{b_1}=e^0=1\)</span>, so no change: <span class="math inline">\(\hat{o}^{(\text{new})}=\hat{o}^{(\text{old})}\)</span>;</li>
<li class="fragment">If <span class="math inline">\(b_1&gt;0\)</span>, then <span class="math inline">\(e^{b_1}&gt;1\)</span>, so <span class="math inline">\(\hat{o}^{(\text{new})}\)</span> is <em>higher</em>;</li>
<li class="fragment">If <span class="math inline">\(b_1&lt;0\)</span>, then <span class="math inline">\(0&lt;e^{b_1}&lt;1\)</span>, so <span class="math inline">\(\hat{o}^{(\text{new})}\)</span> is <em>lower</em>.</li>
</ul></section><section id="for-our-example-1" class="slide level2"><h2>For our example</h2>
<p><span class="math display">\[
\log\left(\frac{\hat{p}}{1-\hat{p}}\right)
=
-2.27
+
0.000272\times exclaim~mess
\]</span></p>
<p>If the email has an additional exclamation mark, we predict the odds of an email being spam to be <strong>higher</strong> by a multiplicative factor of <span class="math inline">\(e^{0.000272}\approx 1.000272\)</span> on average.</p>
</section><section id="how-does-the-probability-adjust" class="slide level2 scrollable"><h2>How does the probability adjust?</h2>
<p>At <span class="math inline">\(x\)</span>, you predict:</p>
<p><span class="math display">\[
\hat{p}^{(\text{old})} = \frac{e^{b_0+b_1x}}{1+e^{b_0+b_1x}}
\]</span></p>
<p>At <span class="math inline">\(x + 1\)</span>, you predict:</p>
<p><span class="math display">\[
\hat{p}^{(\text{new})} = \frac{e^{b_0+b_1(x+1)}}{1+e^{b_0+b_1(x+1)}}
\]</span></p>
<p>This one is tougher. You are not responsible for it, but if you really want to know, the math is relatively painless if you’re into that sort of thing:</p>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>How are <span class="math inline">\(\hat{p}^{(\text{old})}\)</span> and <span class="math inline">\(\hat{p}^{(\text{new})}\)</span> related?</strong></p>
</div>
<div class="callout-content">
<p>Like this:</p>
<p><span class="math display">\[
\hat{p}^{(\text{new})} = \frac{e^{b_1}\hat{p}^{(\text{old})}}{1-\hat{p}^{(\text{old})}+e^{b_1}\hat{p}^{(\text{old})}}
\]</span></p>
<p>The adjustment depends on the <span class="math inline">\(x\)</span> you are starting from, just like we saw in the picture.</p>
</div>
</div>
</div>
</div>
</section><section id="summary" class="slide level2"><h2>Summary</h2>
<ul>
<li>The “intercept” coefficient <span class="math inline">\(b_0\)</span> can be transformed into <span class="math inline">\(\frac{e^{b_0}}{1+e^{b_0}}\)</span>, which is directly interpretable as the predicted <em>probability</em> that <span class="math inline">\(y=1\)</span> when <span class="math inline">\(x=0\)</span>;</li>
<li>The “slope” coefficient <span class="math inline">\(b_1\)</span> is more delicate. It can be transformed into <span class="math inline">\(e^{b_1}\)</span>, which is interpretable as the <em>multiplicative</em> adjustment in the predicted <em>odds</em> when we go from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span>.</li>
</ul></section><section id="summary-three-equivalent-representations" class="slide level2 small"><h2>Summary: three equivalent representations</h2>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 34%">
<col style="width: 19%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th>Version</th>
<th>equation</th>
<th>Friendly LHS?</th>
<th>Friendly RHS?</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Probability: (0, 1)</td>
<td><span class="math display">\[\hat{p}=\frac{e^{b_0+b_1x}}{1+e^{b_0+b_1x}}\]</span></td>
<td>✅</td>
<td>❌</td>
</tr>
<tr class="even">
<td>Odds: <span class="math inline">\((0,\,\infty)\)</span>
</td>
<td><span class="math display">\[\hat{o}=\frac{\hat{p}}{1-\hat{p}}=e^{b_0+b_1x}\]</span></td>
<td>🥴</td>
<td>🥴</td>
</tr>
<tr class="odd">
<td>Log-odds: <span class="math inline">\((-\infty,\,\infty)\)</span>
</td>
<td><span class="math display">\[\log(\hat{o})=b_0+b_1x\]</span></td>
<td>❌</td>
<td>✅</td>
</tr>
</tbody>
</table>
<p>Take your pick depending on what you’re trying to do.</p>
</section></section><section><section id="classification" class="title-slide slide level1 center"><h1>Classification</h1>

</section><section id="classification-1" class="slide level2"><h2>Classification</h2>
<p>We have this model:</p>
<p><span class="math display">\[
\hat{p}=\widehat{\text{Prob}(y=1\mid x)} = \frac{e^{b_0+b_1x}}{1+e^{b_0+b_1x}}.
\]</span></p>
<p>Given <span class="math inline">\(x\)</span>, we predict the <em>probability</em> that <span class="math inline">\(y=1\)</span>. But…so? If you hand me <span class="math inline">\(x\)</span>, is <span class="math inline">\(y=1\)</span> or not? How can we use this model to produce a concrete <em>prediction</em> for the <em>value</em> of <span class="math inline">\(y\)</span>? Behold…</p>
</section><section id="step-0-fit-the-model" class="slide level2 smaller"><h2>Step 0: fit the model</h2>
<p>Select a number <span class="math inline">\(0 &lt; p^* &lt; 1\)</span>:</p>

<img data-src="09-logistic-1_files/figure-revealjs/step-0-1.png" width="960" class="r-stretch"><ul>
<li>if <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>, then predict <span class="math inline">\(\widehat{y}=0\)</span>;</li>
<li>if <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>, then predict <span class="math inline">\(\widehat{y}=1\)</span>.</li>
</ul></section><section id="step-1-pick-a-threshold" class="slide level2 smaller"><h2>Step 1: pick a threshold</h2>
<p>Select a number <span class="math inline">\(0 &lt; p^* &lt; 1\)</span>:</p>

<img data-src="09-logistic-1_files/figure-revealjs/step-1-1.png" width="960" class="r-stretch"><ul>
<li>if <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>, then predict <span class="math inline">\(\widehat{y}=0\)</span>;</li>
<li>if <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>, then predict <span class="math inline">\(\widehat{y}=1\)</span>.</li>
</ul></section><section id="step-2-find-the-decision-boundary" class="slide level2 smaller"><h2>Step 2: find the “decision boundary”</h2>
<p>Solve for the x-value that matches the threshold:</p>

<img data-src="09-logistic-1_files/figure-revealjs/step-2-1.png" width="960" class="r-stretch"><ul>
<li>if <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>, then predict <span class="math inline">\(\widehat{y}=0\)</span>;</li>
<li>if <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>, then predict <span class="math inline">\(\widehat{y}=1\)</span>.</li>
</ul></section><section id="step-3-classify-a-new-arrival" class="slide level2 smaller"><h2>Step 3: classify a new arrival</h2>
<p>A new person shows up with <span class="math inline">\(x_{\text{new}}\)</span>. Which side of the boundary are they on?</p>

<img data-src="09-logistic-1_files/figure-revealjs/step-3-1.png" width="960" class="r-stretch"><ul>
<li>if <span class="math inline">\(x_{\text{new}} \leq x^\star\)</span>, then <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>, so predict <span class="math inline">\(\widehat{y}=0\)</span> for the new person;</li>
<li>if <span class="math inline">\(x_{\text{new}} &gt; x^\star\)</span>, then <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>, so predict <span class="math inline">\(\widehat{y}=1\)</span> for the new person.</li>
</ul></section><section id="lets-change-the-threshold" class="slide level2 smaller"><h2>Let’s change the threshold</h2>
<p>A new person shows up with <span class="math inline">\(x_{\text{new}}\)</span>. Which side of the boundary are they on?</p>

<img data-src="09-logistic-1_files/figure-revealjs/lower-threshold-1.png" width="960" class="r-stretch"><ul>
<li>if <span class="math inline">\(x_{\text{new}} \leq x^\star\)</span>, then <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>, so predict <span class="math inline">\(\widehat{y}=0\)</span> for the new person;</li>
<li>if <span class="math inline">\(x_{\text{new}} &gt; x^\star\)</span>, then <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>, so predict <span class="math inline">\(\widehat{y}=1\)</span> for the new person.</li>
</ul></section><section id="lets-change-the-threshold-1" class="slide level2 smaller"><h2>Let’s change the threshold</h2>
<p>A new person shows up with <span class="math inline">\(x_{\text{new}}\)</span>. Which side of the boundary are they on?</p>

<img data-src="09-logistic-1_files/figure-revealjs/higher-threshold-1.png" width="960" class="r-stretch"><ul>
<li>if <span class="math inline">\(x_{\text{new}} \leq x^\star\)</span>, then <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>, so predict <span class="math inline">\(\widehat{y}=0\)</span> for the new person;</li>
<li>if <span class="math inline">\(x_{\text{new}} &gt; x^\star\)</span>, then <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>, so predict <span class="math inline">\(\widehat{y}=1\)</span> for the new person.</li>
</ul></section><section id="nothing-special-about-one-predictor" class="slide level2 smaller"><h2>Nothing special about one predictor…</h2>
<p>Two numerical predictors and one binary response:</p>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-18-1.png" width="960" class="r-stretch"></section><section id="multiple-logistic-regression" class="slide level2"><h2>“Multiple” logistic regression</h2>
<p>For the log-odds, a <em>multiple</em> linear regression:</p>
<p><span class="math display">\[
\log\left(\frac{p}{1-p}\right)
=
\beta_0+\beta_1x_1+\beta_2x_2+...+\beta_mx_m.
\]</span> On the probability scale:</p>
<p><span class="math display">\[
\text{Prob}(y = 1 \mid x)
=
\frac{e^{\beta_0+\beta_1x_1+\beta_2x_2+...+\beta_mx_m}}{1+e^{\beta_0+\beta_1x_1+\beta_2x_2+...+\beta_mx_m}}.
\]</span></p>
</section><section id="decision-boundary-again" class="slide level2 smaller"><h2>Decision boundary, again</h2>
<p>It’s linear! Consider two numerical predictors:</p>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-19-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><ul>
<li>if new <span class="math inline">\((x_1,\,x_2)\)</span> below, <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>. Predict <span class="math inline">\(\widehat{y}=0\)</span> for the new person;</li>
<li>if new <span class="math inline">\((x_1,\,x_2)\)</span> above, <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>. Predict <span class="math inline">\(\widehat{y}=1\)</span> for the new person.</li>
</ul></section><section id="decision-boundary-again-1" class="slide level2 smaller"><h2>Decision boundary, again</h2>
<p>It’s linear! Consider two numerical predictors:</p>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-20-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><ul>
<li>if new <span class="math inline">\((x_1,\,x_2)\)</span> below, <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>. Predict <span class="math inline">\(\widehat{y}=0\)</span> for the new person;</li>
<li>if new <span class="math inline">\((x_1,\,x_2)\)</span> above, <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>. Predict <span class="math inline">\(\widehat{y}=1\)</span> for the new person.</li>
</ul></section><section id="decision-boundary-again-2" class="slide level2 smaller"><h2>Decision boundary, again</h2>
<p>It’s linear! Consider two numerical predictors:</p>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-21-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><ul>
<li>if new <span class="math inline">\((x_1,\,x_2)\)</span> below, <span class="math inline">\(\text{Prob}(y=1)\leq p^*\)</span>. Predict <span class="math inline">\(\widehat{y}=0\)</span> for the new person;</li>
<li>if new <span class="math inline">\((x_1,\,x_2)\)</span> above, <span class="math inline">\(\text{Prob}(y=1)&gt; p^*\)</span>. Predict <span class="math inline">\(\widehat{y}=1\)</span> for the new person.</li>
</ul></section><section id="note-the-classifier-isnt-perfect" class="slide level2 medium"><h2>Note: the classifier isn’t perfect</h2>

<img data-src="09-logistic-1_files/figure-revealjs/unnamed-chunk-22-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><ul>
<li>There are blue points in the orange region: spam (1) emails misclassified as legit (0);</li>
<li>There are orange points in the blue region: legit (0) emails misclassified as spam (1).</li>
</ul></section><section id="how-do-you-pick-the-threshold" class="slide level2 smaller"><h2>How do you pick the threshold?</h2>
<p>To balance out the two kinds of errors:</p>

<img data-src="images/09/confusion-matrix.png" class="r-stretch"><ul>
<li>High threshold &gt;&gt; Hard to classify as 1 &gt;&gt; FP less likely; FN more likely;</li>
<li>Low threshold &gt;&gt; Easy to classify as 1 &gt;&gt; FP more likely; FN less likely;</li>
<li>You don’t want to make mistakes of either kind, you it’s always a balancing act.</li>
</ul></section><section id="silly-examples" class="slide level2"><h2>Silly examples</h2>
<ul>
<li>
<p>Set p* = 0</p>
<ul>
<li>Classify every email as spam (1);</li>
<li>No false negatives, but <em>a lot</em> of false positives;</li>
</ul>
</li>
<li>
<p>Set p* = 1</p>
<ul>
<li>Classify every email as legit (0);</li>
<li>No false positives, but <em>a lot</em> of false negatives.</li>
</ul>
</li>
</ul>
<p>You pick a threshold in between to strike a balance. The exact number depends on context.</p>
</section></section><section id="now-off-to-your-container" class="title-slide slide level1 center"><h1>Now, off to your container!</h1>


</section>
</div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://sta101-f26.github.io/">🔗 sta101-f26.github.io</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="../site_libs/revealjs/dist/reveal.js"></script><!-- reveal.js plugins --><script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script><script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script><script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script><script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script><script src="../site_libs/revealjs/plugin/notes/notes.js"></script><script src="../site_libs/revealjs/plugin/search/search.js"></script><script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script><script src="../site_libs/revealjs/plugin/math/math.js"></script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script><script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script><script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/sta101-f26\.github\.io\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>


</body></html>