---
title: "Course overview"
editor: 
  mode: source
---

# Description

**What the course catalog says** ([source](https://stat.duke.edu/courses/data-analysis-and-statistical-inference-0)): Introduction to statistics as a science of understanding and analyzing data. Themes include data collection, exploratory analysis, inference, and modeling. Focus on principles underlying quantitative research in social sciences, humanities, and public policy. Research projects teach the process of scientific discovery and synthesis and critical evaluation of research and statistical arguments. Readings give perspective on why in 1950, S. Wilks said, "Statistical thinking will one day be as necessary a qualification for efficient citizenship as the ability to read and write."

**Prerequisites:** a body temperature roughly in the nineties.

# Meetings

| Meeting  | Location                       | Time                   | Staff  |
|----------|--------------------------------|------------------------|--------|
| Lectures | Social Sciences 139        | TuTh 3:05 PM - 4:20 PM | JZ, Christina   |
| Lab 01   | Old Chem 201 | F 10:05 AM - 11:20 AM   | Songliang, Sonya |
| Lab 02   | Old Chem 201 | F 11:45 AM - 01:00 PM   | Songliang, Matthew |
| Lab 03   | Old Chem 201 | F 01:25 PM - 02:40 PM   | Songliang, Matthew |
: {tbl-colwidths="[25, 25, 25, 25]"}