---
title: "Assignments and grading"
editor: 
  mode: source
---

Your final course grade will be calculated as follows:

::: {.center-table}
| Category       | Percentage |
|----------------|------------|
| Labs           | 10%        |
| Homeworks      | 20%        |
| Project        | 20%        |
| Midterm Exam   | 25%        |
| Final exam     | 25%        |
:::

Your final letter grade will be determined based on the usual thresholds:

::: {.center-table}
| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |
:::

::: callout-warning
## What you see is what you get
These thresholds will not change, and they will be applied exactly. This means that the final grades will not be curved, and a 92.99, for example, will not be rounded up to an A.
:::

## Labs (10%)

In your lab section each Friday, you will get into randomly assigned groups and complete a guided activity that gives you practice with the new material introduced in lecture that week. Your lab write-up is due at the end of your lab section, and late work will not be accepted. 

::: callout-note
## Grace

There will be ten graded labs in total, and your two lowest lab scores will be dropped at the end of the semester.
:::

## Homeworks (20%)

If you practice, you improve. That's true about pretty much everything, and data analysis is no exception. As such, the homeworks are the most important course component. If you skimp on these, it will not redound to your benefit on the exams. The homework assignments will be a mix of coding problems in R and exercises from [our textbook](https://openintrostat.github.io/ims/). These will have one week turnaround: each assignment will be posted on a Friday, and will be due at 10:00 AM the following Friday. 

::: callout-note
## Grace

There will be eight homeworks in total, and your lowest homework score will be dropped at the end of the semester.
:::

## Group data analysis project (20%)

The project will be completed in teams that are randomly assigned within your lab section. As a group you will select a dataset that interests you and then apply what you've learned throughout the semester to study a research question of your choosing. This will culminate in the following deliverables:

- **Final presentation**: a five minute slide talk given in your lab on Friday December 4 (LDOC);
- **Final report**: a written report submitted the following Monday December 7 (when?).

There will be other intermediate deadlines along the way to keep you on track. More information about the project will be provided in lab on Friday October 16.


::: callout-warning
## You can't skip this!

Regardless your enrollment status (e.g. [S/U](https://trinity.duke.edu/undergraduate/academic-policies/unsatisfactory-satisfactory-grading-option)), I will not give you a passing grade if you do not complete the group project.

:::


## Exams (25% each)

There will be two in-person exams. The dates, times, and locations are firm, so mark your calendar now:

-   **Midterm** (25%): Thursday October 8, 3:05 PM - 4:20 PM in Social Sciences 139;
-   **Final** (25%): Thursday December 10, 2:00 PM - 5:00 PM in Social Sciences 139.

These will be old school, pencil-and-paper, in-class exams with no technology. The only resource you are allowed is both sides of one 8.5" x 11" sheet of notes, prepared by you and you alone. You can create it however you wish: handwritten, on a computer, on a tablet device, etc.

If you seek testing accommodations, make sure the Student Disability Access Office sends me a letter, and then please make your appointments in the [Testing Center](https://testingcenter.duke.edu) as soon as possible.

::: callout-note
## Grace

If you do better on the final exam than you did on the midterm, I will replace your midterm score with your final exam score.
:::

::: callout-warning
## No make-up exams

If you are absent from the midterm for whatever reason, there will not be a make-up. Pursuant to the above policy, I will simply replace the missed midterm score with the final exam score. If you miss the final exam, you get a zero unless you have a [Dean's Excuse](https://trinity.duke.edu/undergraduate/academic-policies/final-exams-scheduling-conflicts-and-absences).
:::
