---
title: "Policies"
editor: 
  mode: source
---

## Attendance

Lecture attendance is not required, and I am not tracking or enforcing it in any way. The responsibility lies with me to make class sufficiently engaging and informative that you choose to attend. That said, you will probably do better in this class if you attend lecture regularly. I leave it to you to be a grown-up and make a decision.

Lab attendance on the other hand is required in order to receive credit for the assignments. Since lab work is always completed in teams, you can't get credit if you leave your team hanging by not attending. There are ten graded labs in total, and we drop your two lowest scores at the end of the semester. We will use this policy to automatically absorb the effect of one-off absences due to brief illness, travel, job interviews, etc. If more challenging or protracted circumstances arise (e.g. bereavement or serious illness) that affect your lab attendance, please secure a [dean's excuse](https://trinity.duke.edu/undergraduate/academic-policies/class-attendance-and-missed-work) and then reach out to the instructor directly (john.zito\@duke.edu) to discuss special arrangements.

## Collaboration

Collaboration is simply *required* on labs and the project. It is *forbidden* on the exams. It is *enthusiastically encouraged* on homeworks. You will learn a lot from helping each other. I would much rather you consult your peers than some daft language model. What I ask is that you *acknowledge* your collaborators. So, at the top of your write-up, leave a bulleted list of comments like "Ursula, Ignatius and I worked together on this problem," or "Ethel explained to me how to do part b." You are not being judged based on your acknowledgements, and there is no penalty for getting "too much" help from others. If you omit acknowledgements, I will assume you did your work solo. If your classmates tell a different story, I will have questions. But otherwise, so long as you are thorough and honest, there will be no problems.

Having said all of that, you should not be crassly handing your solutions to others for them to brainlessly copy. This is plagiarism, and all involved will earn a zero on the assignment and be referred to the conduct office, both sharers and recipients alike. The write-up you submit must be your own work.

## Use of outside resources, including AI

You may make use of any online resources (e.g. `StackOverflow`) but you must explicitly cite where you obtained any code you directly use (or use as inspiration). Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

You should treat generative AI, such as ChatGPT, like other online resources. Two guiding principles govern how to use AI in this course:

1.  *Cognitive dimension:* "[Using ChatGPT to complete assignments is like bringing a forklift into the weight room; you will never improve your cognitive fitness that way](https://www.newyorker.com/culture/the-weekend-essay/why-ai-isnt-going-to-make-art)." Furthermore, 50% of your final course grade is determined by your performance on old school, no-tech exams. As such, outsourcing all of your *thinking* to an AI will probably end in humiliating disaster. To avoid this, I suggest you abstain from using language models to do the homework for you;

2.  *Ethical dimension***:** Students using AI should be transparent about their use and ensure it aligns with academic integrity.

-   {{< fa check >}} **AI tools for code:** You may use the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. The bare minimum citation must include the AI tool you're using (e.g., ChatGPT), the text of your prompt, and a direct url to the conversation you had. The prompt you use cannot be copied and pasted directly from the assignment; you must create a prompt yourself.

-   {{< fa ban >}} **AI tools for narrative:** Unless instructed otherwise, you may not use generative AI to generate a narrative that you then copy-paste verbatim into an assignment or edit and then insert into your assignment.

In general, you may use generative AI as a resource as you complete assignments but not to answer the exercises for you. You are ultimately responsible for the work you turn in; it should reflect *your* understanding of the course content. Identifying AI-generated content is fairly straightforward. Any code identified as AI-generated but not cited as such and any narrative identified as AI-generated will be considered plagiarism and treated as such.

## Communication

If you wish to ask content-related questions in writing, please do not do so via e-mail. Instead, please use the course discussion forum [Ed Discussion](https://edstem.org/us/courses/101045/discussion). That way all members of the teaching team can see your question, and all students can benefit from the ensuing discussion. You are also encouraged to answer one another’s questions. **Note**: You can ask questions anonymously on Ed. The teaching team will still know your identity, but your peers will not.

If you have questions about personal matters that may not be appropriate for the public course forum (e.g. illness, accommodations, etc), then please e-mail the instructor directly (john.zito\@duke.edu).

::: callout-warning
You should not be e-mailing the TAs directly for any reason. If you do, they will just forward it to me.
:::

## Late work and extensions

No late work will be accepted unless you request an extension in advance by e-mailing the instructor directly (john.zito\@duke.edu). All reasonable requests will be entertained, but extensions will not be long.

## Regrade requests

If you receive a graded assignment back, and you believe that some part of it was graded incorrectly, you may dispute the grade by submitting a [regrade request](https://guides.gradescope.com/hc/en-us/articles/21854736042253-Submitting-a-Regrade-Request) in Gradescope. JZ is the sole reviewer of these. Note the following:

-   You have one week after you receive a grade to submit a regrade request;
-   You should submit separate regrade requests for each question you wish to dispute, not a single catch-all request;
-   Requests will be considered if there was an error in the grade calculation or if a correct answer was mistakenly marked as incorrect;
-   Requests to dispute the number of points deducted for an incorrect response will not be considered;
-   **No grades will be changed after the final exam has been administered on Thursday December 10**.

## Accommodations

### Academic

If you seek accommodations for this class, you will need to register with the Student Disability Access Office (SDAO) and provide them with documentation related to your needs. SDAO will work with you to determine what accommodations are appropriate for your situation. Please note that accommodations are not retroactive and disability accommodations cannot be provided until a Faculty Accommodation Letter has been given to me. Please contact SDAO for more information: `sdao@duke.edu` or `access.duke.edu`.

### Religious

Students are permitted by university policy to be absent from class to observe a religious holiday.
Accordingly, Trinity College of Arts & Sciences and the Pratt School of Engineering have established procedures to be followed by students for notifying their instructors of an absence necessitated by the observance of a religious holiday.
Please submit requests for religious accommodations at the beginning of the semester so that we can work to make suitable arrangements well ahead of time.
You can find the policy and relevant notification form here: [trinity.duke.edu/undergraduate/academic-policies/religious-holidays](https://trinity.duke.edu/undergraduate/academic-policies/religious-holidays)


## Duke Community Standard

Duke University is a community dedicated to scholarship, leadership, and service and to the principles of honesty, fairness, respect, and accountability. Members of this community commit to reflect upon and uphold these principles in all academic and non-academic endeavors, and to protect and promote a culture of integrity. Duke University has high expectations for students’ scholarship and conduct. In accepting admission, students indicate their willingness to subscribe to and be governed by the rules and regulations of the university, which flow from the [Duke Community Standard (DCS)](https://dukecommunitystandard.students.duke.edu). Regardless of course delivery format, it is the responsibility of all students to understand and follow all Duke policies, including but not limited to the [academic integrity policy](https://dukecommunitystandard.students.duke.edu/policy/academic-dishonesty/) (e.g. completing one’s own work, following proper citation of sources, adhering to guidance around group work projects, and more). Ignoring these requirements is a violation of the DCS. Students can direct any questions or concerns regarding academic integrity to the Office of Student Conduct and Community Standards at `conduct@duke.edu` and can access the DCS guide at <https://dukecommunitystandard.students.duke.edu/>.

### Fine fine, but what does that mean in STA 101?

If you submit work and I detect any violation of Duke's academic honesty standards or of our course policies, it will automatically results in a zero for the relevant portion or the entire assignment, and I will immediately file a [report](https://cm.maxient.com/reporting.php?DukeUniv) with the Office of Student Conduct & Community Standards for further action. Furthermore:

-   If a conduct violation results in a zero on a lab or homework, that zero will not be dropped;
-   If a conduct violation results in a zero on the midterm, that zero will not be replaced with your final exam score;
-   If we discover that students are sharing and copying assignment solutions, all students involved will be penalized equally, the sharers the same as the recipients.
